### ISSUE TITLE
有定时删除功能吗？若无，希望增加。

### ISSUE THREAD

**Issue by supercatreal** [kakkk/PHP-BingWallpaper#1]
定时删除缓存的文件可以很好的节省小服务器的空间。

**Comment by kakkk** [comment]
可以自己改的，也不难。
这个玩意主要是我自己用的分享出来，所以也不打算更新了哈

**Comment by kakkk** [comment]
> 定时删除缓存的文件可以很好的节省小服务器的空间。

可以自己改的，也不难。
这个玩意主要是我自己用的分享出来，所以也不打算更新了哈
